# Generated by Django 5.2.12 on 2026-04-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_contacto',
            field=models.CharField(choices=[('NO', 'No'), ('LLAMA_JUAN', 'Si Llama Juan'), ('LLAMA_ALEX', 'Si Llama Alex'), ('SMS_ALEX', 'Se envia SMS ALEX'), ('SMS_JUAN', 'Se envia SMS Juan')], default='NO', max_length=30),
        ),
    ]
