# Generated by Django 5.2.12 on 2026-05-02 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_observaciones_anteriores(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    ObservacionCliente = apps.get_model("clientes", "ObservacionCliente")

    for cliente in Cliente.objects.exclude(observaciones="").order_by("pk"):
        texto = (cliente.observaciones or "").strip()
        if texto and not ObservacionCliente.objects.filter(cliente=cliente, texto=texto).exists():
            ObservacionCliente.objects.create(cliente=cliente, texto=texto)


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_estado_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_historial', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observacion del cliente',
                'verbose_name_plural': 'Observaciones del cliente',
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
        migrations.RunPython(migrar_observaciones_anteriores, migrations.RunPython.noop),
    ]
