# Generated by Django 5.2.12 on 2026-04-14 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
        ('inventario', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso de mercaderia'), ('TRANSFERENCIA', 'Traslado entre ubicaciones')], default='INGRESO', max_length=20)),
                ('ubicacion_origen', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('LOCAL', 'Local')], max_length=20)),
                ('ubicacion_destino', models.CharField(choices=[('CASA', 'Casa'), ('LOCAL', 'Local')], default='CASA', max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.CharField(blank=True, max_length=255)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('aplicado', models.BooleanField(default=False, editable=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='catalogo.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(choices=[('CASA', 'Casa'), ('LOCAL', 'Local')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_ubicacion', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Stock por ubicacion',
                'verbose_name_plural': 'Stock por ubicacion',
                'ordering': ['producto__nombre', 'ubicacion'],
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
    ]
