# Generated by Django 5.2.12 on 2026-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_minimo_porcentaje',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
