# Generated by Django 5.2.12 on 2026-04-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_promocion', models.CharField(choices=[('FRECUENCIA', 'Cliente frecuente'), ('VOLUMEN', 'Volumen de compra'), ('FECHA_ESPECIAL', 'Fecha especial'), ('INACTIVIDAD', 'Cliente inactivo'), ('PRODUCTO', 'Por producto'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('condicion_aplicacion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
    ]
