# Generated by Django 5.2.12 on 2026-04-13 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_interaccion', models.CharField(choices=[('LLAMADA', 'Llamada'), ('MENSAJE', 'Mensaje'), ('VISITA', 'Visita'), ('OBSERVACION', 'Observacion')], default='OBSERVACION', max_length=20)),
                ('observacion', models.TextField()),
                ('fecha_interaccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Seguimiento de cliente',
                'verbose_name_plural': 'Seguimientos de clientes',
                'ordering': ['-fecha_interaccion'],
            },
        ),
    ]
