# Generated by Django 5.2.12 on 2026-04-14 14:46

import apps.seguimiento.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_apellidos_alter_cliente_identificacion_and_more'),
        ('seguimiento', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientocliente',
            options={'ordering': ['-fecha_cita', '-fecha_interaccion'], 'verbose_name': 'Seguimiento de cliente', 'verbose_name_plural': 'Seguimientos de clientes'},
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='asunto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='carpeta_tratamiento',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AGENDADO', 'Agendado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='fecha_cita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='proximo_contacto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seguimientocliente',
            name='tratamiento_aceptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seguimientocliente',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='seguimientocliente',
            name='tipo_interaccion',
            field=models.CharField(choices=[('LLAMADA', 'Llamada'), ('CITA', 'Cita'), ('ENVIO_FOTOS', 'Envio de fotos'), ('SEGUIMIENTO', 'Seguimiento')], default='SEGUIMIENTO', max_length=20),
        ),
        migrations.CreateModel(
            name='FotoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.seguimiento.models.ruta_foto_seguimiento)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviado_al_cliente', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_seguimiento', to='clientes.cliente')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='seguimiento.seguimientocliente')),
            ],
            options={
                'verbose_name': 'Foto de seguimiento',
                'verbose_name_plural': 'Fotos de seguimiento',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
