# Generated by Django 5.2.12 on 2026-04-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_alter_seguimientocliente_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientocliente',
            name='tipo_interaccion',
            field=models.CharField(choices=[('LLAMADA', 'Llamada'), ('CITA', 'Cita'), ('ENVIO_FOTOS', 'Envio de fotos'), ('FOTOS_PENDIENTES', 'Fotos pendientes'), ('SEGUIMIENTO', 'Seguimiento')], default='SEGUIMIENTO', max_length=20),
        ),
    ]
